# Generated by Django 4.2 on 2023-05-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-is_completed"]},
        ),
        migrations.AddField(
            model_name="task",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
